# Generated by Django 5.0.6 on 2024-07-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=15)),
                ('nm', models.CharField(max_length=15)),
                ('em', models.EmailField(max_length=254)),
                ('psw', models.CharField(max_length=15)),
                ('cpsw', models.CharField(max_length=15)),
            ],
        ),
    ]
