# Generated by Django 5.0.6 on 2024-07-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='em',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='n',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='nm',
            new_name='lastname',
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
