# Generated by Django 5.0.6 on 2024-07-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_addproduct_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproduct',
            name='athr',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
