# Generated by Django 5.0.6 on 2024-07-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_addproduct_athr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='cat',
            field=models.CharField(choices=[('Thriller', 'Thriller'), ('Mystery', 'Mystery'), ('Horror', 'Horror'), ('Comics', 'Comics'), ('Adventure', 'Adventure'), ('Romance', 'Romance'), ('Historical fiction', 'Historical fiction'), ('Literary fiction', 'Literary fiction'), ('Science Fiction', 'Science Fiction'), ('Autobiography', 'Autobiography'), ('Memoir', 'Memoir'), ('History', 'History'), ('Travel', 'Travel'), ('Science', 'Science'), ('Philosophy', 'Philosophy'), ('Essays', 'Essays'), ('Business', 'Business'), ("Children's Book", "Children's Book"), ('Classic Literature', 'Classic Literature'), ('Short Stories', 'Short Stories'), ('Drama', 'Drama'), ('Poetry', 'Poetry'), ('Self-help and Motivational', 'Self-help and Motivational')], max_length=40),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='lang',
            field=models.CharField(choices=[('English', 'English'), ('Malayalam', 'Malayalam')], max_length=15),
        ),
    ]
