# Generated by Django 5.0.6 on 2024-08-01 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='pr',
            field=models.IntegerField(),
        ),
    ]
