# Generated by Django 5.0.6 on 2024-08-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_orderplaced_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On the Way', 'On The Way'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Packed', 'Packed'), ('Accepted', 'Accepted')], default='pending', max_length=50),
        ),
    ]
