# Generated by Django 5.0.6 on 2024-08-20 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_orderplaced_status_payment_orderplaced_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='buy_now_product_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.addproduct'),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Cancel', 'Cancel'), ('On the Way', 'On The Way'), ('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Delivered', 'Delivered')], default='pending', max_length=50),
        ),
    ]
