# Generated by Django 5.0.6 on 2024-08-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_payment_buy_now_product_id_alter_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On the Way', 'On The Way'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Packed', 'Packed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='buy_now_product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
